### Send PUT request with json body
GET http://127.0.0.1:8000/aulario/curso/1/
Accept: application/json


### Send POST request with json body
POST http://127.0.0.1:8000/aulario/curso/
Content-Type: application/json

{
    "name": "2SMRA",
    "capacity": 20,
    "asignaturas_ids": [1,2]
}

### Send POST request with json body
PUT http://127.0.0.1:8000/aulario/curso/2/
Content-Type: application/json

{
    "id": 9,
    "name": "PruebaFinal",
    "capacity": 101010,
    "asignaturas_ids": [1]
}

### Send POST request with json body
POST http://127.0.0.1:8000/aulario/reserva/
Content-Type: application/json

{
    "name": "Nueva Reserva",
    "fecha": "2025-06-03T10:00:00Z",
    "aula_id": 1,
    "curso_id": 1,
    "asignatura_id": 1,
    "usuario_id": 1
}

