### Send PUT request with json body
GET http://127.0.0.1:8000/aulario/curso/1/
Accept: application/json


### Send POST request with json body
PUT http://127.0.0.1:8000/aulario/curso/2/
Content-Type: application/json

{
  "id": 2,
  "name": "2SMRA",
  "capacity": 20,
  "asignaturas": [
    {
      "id": 1,
      "code": "AAC",
      "name": "Adoro Aula Campus"
    }
  ]
}